name: contribute-on-discussion

on:
  discussion:
    types: [created]
jobs:
  handle_contribute:
    runs-on: ubuntu-latest
    if: github.event.discussion && !github.event.comment && github.event.discussion.category.name == '기고채널'
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      OPS_ENV: production
      DISCUSSION_ID: ${{ github.event.discussion.id }}
      DISCUSSION_CATEGORY_NAME: ${{ github.event.discussion.category.name }}
      DISCUSSION_NUMBER: ${{ github.event.discussion.number }}
      DISCUSSION_URL: ${{ github.event.discussion.html_url }}
      DISCUSSION_TITLE: ${{ github.event.discussion.title }}
      DISCUSSION_BODY: ${{ github.event.discussion.body }}
      DISCUSSION_CREATED_AT: ${{ github.event.discussion.created_at }}
      DISCUSSION_USER_URL: ${{ github.event.discussion.user.html_url }}
      DISCUSSION_USER_NAME: ${{ github.event.discussion.user.login }}
      DISCUSSION_USER_AVATAR_URL: ${{ github.event.discussion.user.avatar_url }}
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: ./contribute-handler
        run: |
          npm install
      - name: Fire
        working-directory: ./contribute-handler
        run: |
          npm run start
